---
all:
  children:
    molecule:
      hosts:
        molecule-fedora:
          ansible_connection: containers.podman.podman
          container_image_path: ${MOLECULE_SCENARIO_DIRECTORY}/dockerfiles/fedora42
          container_image_tag: molecule-fedora:42
          container_image: localhost/molecule-fedora:42
          container_command: /sbin/init
          container_privileged: false
          container_rm: true
          container_rmi: false

        molecule-debian:
          ansible_connection: containers.podman.podman
          container_image_path: ${MOLECULE_SCENARIO_DIRECTORY}/dockerfiles/debian13
          container_image_tag: molecule-debian:13
          container_image: localhost/molecule-debian:13
          container_command: /lib/systemd/systemd
          container_privileged: false
          container_rm: true
          container_rmi: false

