---
- name: Load OS-specific vars
  ansible.builtin.include_vars: "../vars/{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yml"

- name: Include Debian 13 tasks
  ansible.builtin.include_tasks: setup-debian-13.yml
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_facts.distribution_major_version | int == 13

- name: Include Fedora 42 tasks
  ansible.builtin.include_tasks: setup-fedora-42.yml
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_facts.distribution_major_version | int == 42

- name: Include Fedora 43 tasks
  ansible.builtin.include_tasks: setup-fedora-43.yml
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_facts.distribution_major_version | int == 43

- name: Enable ip forwarding for exit node
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: false
    sysctl_file: "{{ tailscale_sysctl_file }}"
    state: present
    reload: false
  loop:
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }
  when: tailscale_ip_forwarding_enable | bool
