---
- name: Verify
  hosts: molecule
  gather_facts: true
  vars_files:
    - ../../vars/main.yml
  
  tasks:
  - name: Get information on tailscale repo file
    ansible.builtin.stat:
      path: /etc/yum.repos.d/tailscale.repo
    register: tailscale_repo_file

  - name: Fail if tailscale repo file does not exist
    ansible.builtin.fail:
      msg: "/etc/yum.repos.d/tailscale.repo file does not exist"
    when: not tailscale_repo_file.stat.exists